### ISSUE TITLE
propose pre-generated issues template

### ISSUE THREAD

**Issue by mrturkmen06** [pass-wall/passwall-server#105]
It could be a best practice to use auto generated issues template for creating issues as described over [here](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) 

Of course, it does not mean that it is preventing from opening   blank issue however, when the templates are available, then everyone can easily understand the bug or proposed feature and taking care of any issue might be flawless.

**Comment by yakuter** [comment]
Well I thought about the issue but couldn't find time to add. I saw templates for both bugs and issues. This should be fine. Do you want to work on it?

**Comment by mrturkmen06** [comment]
Yeah, sure.
