### ISSUE TITLE
go-password package implementation

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-server#111]
**Is your feature request related to a problem? Please describe.**
Our random password generator is not good enough.

**Describe the solution you'd like**
There is a good repo [here](https://github.com/sethvargo/go-password). We need its implementation. It is really an easy and quick job to do. We just need to update Password() in /app/encryption.go with someting like this:

```
package main

import (
  "log"
  "github.com/sethvargo/go-password/password"
)

func main() {
  // Generate a password that is 64 characters long with 10 digits, 10 symbols,
  // allowing upper and lower case letters, disallowing repeat characters.
  res, err := password.Generate(64, 10, 10, false, false)
  if err != nil {
    log.Fatal(err)
  }
  log.Printf(res)
}
```

Default configuration (64, 10, 10, false, false) is good for us.

Do anyone want to work on this?

**Comment by mrturkmen06** [comment]
@yakuter 
👋🏻 I can easily take over it.

**Comment by yakuter** [comment]
Thank you. I assigned you now.

**Comment by yakuter** [comment]
This is done with #112
