### ISSUE TITLE
Ping/HealthCheck endpoint needed.

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-server#113]
**Is your feature request related to a problem? Please describe.**
We don't know if the server is running. We need a public (excluded from auth) endpoint to check server status. Then we can use uptimerobot and check the server status regularly.

**Describe the solution you'd like**

We need an endpoint which only returns 200 with a GET method. It should be /ping, /health or /health-check. We can search for best practice about it.

For a better health check, this endpoint can check if postgres or mysql is running and db connection is fine.

**Additional context**
Does anyone want to work on this?

**Comment by mrturkmen06** [comment]
I can take it 👋🏻 
Would it be sufficient to return something like this ; (assumes that mysql service is used, postgres not used )

```
{
	"service": {
		"status": "OK",
		"statusCode": "200",
		"error": "N/A"
	},
	"postgres": {
		"status": "N/A",
		"statusCode": "N/A",
		"error": "N/A"
	},
	"mysql": {
		"status": "OK",
		"statusCode": "200",
		"error": "N/A"
	}
}
```

**Comment by mrturkmen06** [comment]
This (https://github.com/AppsFlyer/go-sundheit) can be used or can be implemented natively it depends how many services will be included in the future. Of course, there might be  a drawback of using external library every time (-it may blow up the binary which is generated at the end.-).

**Comment by yakuter** [comment]
> I can take it 👋🏻
> Would it be sufficient to return something like this ; (assumes that mysql service is used, postgres not used )
> 
> ```
> {
> 	"service": {
> 		"status": "OK",
> 		"statusCode": "200",
> 		"error": "N/A"
> 	},
> 	"postgres": {
> 		"status": "N/A",
> 		"statusCode": "N/A",
> 		"error": "N/A"
> 	},
> 	"mysql": {
> 		"status": "OK",
> 		"statusCode": "200",
> 		"error": "N/A"
> 	}
> }
> ```

We can remove "status" lines. Just status_code and error is fine. Also I think we don't need external lib for this job. Can I assign you with this?

**Comment by mrturkmen06** [comment]
Yeah, I think so as well. As I mentioned importing libraries can blow up binary, no need to import it.

**Comment by yakuter** [comment]
No not urgent. Anytime is fine.
