### ISSUE TITLE
some ideas and questions

### ISSUE THREAD

**Issue by mrturkmen06** [pass-wall/passwall-server#114]
**Is your feature request related to a problem? Please describe.**

It is NOT a feature but could be nice to do, first of all, I am not very deep into project, which means that if I am suggesting something which is not valid or wrong, please let me know and forgive me.  I have following  concerns on overall repo, it may valid or not valid. (depends person to person) However, just wanted to share. 

Concerns; 

-  is not it a little bit odd that `main.go` is under `cmd/pass-wall` folder ?  is there any intention or plan to write down CLI  as well ? 

- I have noticed that all go files  ends with `_api.go` suffix [here](https://github.com/pass-wall/passwall-server/tree/master/internal/api). Is it really necessary ?   Since it is under `api` dir, no need to add suffix. (according to best practices )

- I think, there is an overdue or invalid todo  for instance [here](https://github.com/pass-wall/passwall-server/blob/31127db98112cce2acde909f580d3e5309b30c6a/internal/router/secure.go#L33),  it is deprecated, can be read from [here](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Public-Key-Pins)

**Describe the solution you'd like**

- Move main.go to root directory.  (or prepare a CLI for the repo)
- Remove suffixes from files under `api` dir
- Handle given todo regarding to Public-Key-Pins in different way.

**Comment by furkanbegen** [comment]
There is a nice article about package layout: https://medium.com/@benbjohnson/standard-package-layout-7cdbc8391fc1 

As my understanding, main.go shouldn't be in the root folder other than small projects and  cmd package doesn't has to be CLI related.

**Comment by yakuter** [comment]
Sorry for late response.

1. ./cmd/project-name/main.go is best practice and commone usage for go community. So I chose this way and don't want to change it.

2. We don't need _api suffix as you suggested. We can work on it to change.

3. You are right about it. We can remove that line.

@mrturkmen06 are you available to do these 2 and 3?

**Comment by mrturkmen06** [comment]
yeah sure. However, it may create conflicts. (minor conflicts)

**Comment by yakuter** [comment]
If you don't change package name, then I don't think there should be conflicts. At least I hope so :)

**Comment by mrturkmen06** [comment]
seems it does.
