### ISSUE TITLE
Remove MySQL and SQLite, just support Postgresql idea?

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-server#118]
**Is your feature request related to a problem? Please describe.**
Main issue here is I want to make this backend multi-tenant. The best way to make this is use Postgresql Schemas. This is why I especially want to use Postgresql. Also;

SQLite uses CGO enabled to build which is not suggested.
MySQL's schema logic is normally database logic and I don't think create new database for every users is a way.

**Describe the solution you'd like**
Let's use only postgresql :)

What do you think?

**Comment by yakuter** [comment]
@mrturkmen06 @omerbasoglu-co I wonder your comments?

**Comment by mrturkmen06** [comment]
I think, there is no harm to use only Postgresql, so I agree, but it also depends why mysql and sqlite required and implemented in the project in past, if the response of this question is something which is  overdue or not valid anymore, yeah, it could be better to stick with postgres. 

By the way, I could not notice goroutines within the project, maybe refactoring some functions or portion of code to use goroutines and channels would make it much better. ( - or worse :)  depends on how it is implemented.- ). Of course, having goroutines is increasing likelihood of having more errors, if and only if the test cases will not be pushed along code. (even in those cases, there might be leaked bugs, but I think, it comes from nature of software development.)

**Comment by yakuter** [comment]
Well, there must be only one goroutine at auto backup. If it is needed of course we must use however I didn't have a chance to think about it clearly.

By the way I removed SQLite and MySQL support. We never needed them in the begining. Also I updated test workflow and health check database information. The workflow is great, thank you again :)
