### ISSUE TITLE
Docker run error

### ISSUE THREAD

**Issue by yusufpapurcu** [pass-wall/passwall-server#129]
**Describe the bug**
I'm trying this 
`docker pull passwall/passwall-server`

`cp ./store/config-sample.yml ./store/config.yml`

`docker run --name passwall-server --rm -v $(pwd)/store:/app/store -p 3625:3625 passwall/passwall-server`

and getting 
`standard_init_linux.go:211: exec user process caused "no such file or directory"`

 - OS: Arch linux
 - Version: 5.6.16-1-MANJARO
- Docker Version: 9.03.11-ce

I'm tried with `go run ` and it's working.

**Comment by mrturkmen06** [comment]
I have proposed the change, now it should not complain about that issue @yusufpapurcu . Could you test it and confirm that it is working ?

**Comment by mrturkmen06** [comment]
Btw, another alternative solution could be re-introduce alpine base image in Dockerfile [here](https://github.com/pass-wall/passwall-server/blob/aaf8d068ea7ce387b48f3d10dfdfc0a21f343940/Dockerfile#L17)

**Comment by yusufpapurcu** [comment]
Yes it's working now. Thanks.
