### ISSUE TITLE
How to backup?

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-server#29]
API needs a backup plan. Any ideas? For SQL lite file, it can be stored (icloud, google folder etc.) anywhere but what about Postgres and MySQL databases? I think there can be a cron job which gets the backup of dataabse table.

**Comment by murat** [comment]
Maybe a cron would be nice to create database dumps and sync with a drive.
Also, there would be an option to import/export from/to another password managers.

**Comment by yakuter** [comment]
Cron job to a folder, drive etc. is a good idea. I was thinking the same. However I just added a simple Backup and Restore features. They have endpoints (/logins/backup, /logins/restore). They basically exports all logins to an encrypted file in ./store folder and restores from it.

Well there is already import/export. You can see in the API documentation.

**Comment by murat** [comment]
Yep, I know the import/export endpoints but I meant directly import from another PM.

**Comment by yakuter** [comment]
This issue is about backup and I am closing it. The another subject about direct importing which @murat said is true. We need something like this. I am going to open anoter issue for this.
