### ISSUE TITLE
Endpoint tests need SQL mock with Gorm

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-server#39]
In main_test.go file, there are some tests. However those test should be written with SQL mock using Gorm DB model.

**Comment by mrturkmen06** [comment]
Hi @yakuter, 

I have just looked at for the file `main_test.go` under this project, however, seems it does not exist. Am i missing something or is this issue  outdated ? 

Apart from that, it would be nice to have a chat space (such as gitter ) where anyone who would like to contribute to project might ask questions before hand and it can lead more collaborative working environment. I think, it can also  prevent to have polluted issues which are not required for the project.  Of course, it really depends on availability of core team members of this project, but it is just a suggestion. (there is no right or wrong :) )

**Comment by mrturkmen06** [comment]
I think, this is overdue. 

@yakuter

**Comment by yakuter** [comment]
Yeah
