### ISSUE TITLE
Move from Gin framework to native net/http

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-server#75]
Gin is really limiting us. We are moving to native net/http and mux router. We are going to use these tools:

net/http
mux router
jwt-go with HMAC signing (https://github.com/dgrijalva/jwt-go)
Negroni for middlewares

I started working on this. 1 or 2 day later it will be finished.

**Comment by musabgultekin** [comment]
Where does it limits? Gin is known of being flexible. This conversion could cause much more trouble than it brings. Because  mux router and net/http is low level and there will be many things to write like reinventing the wheel on things.

**Comment by yakuter** [comment]
Well, gin has lots of features but we use only a little of them. So it is not necessary at all. I already converted all the functions. Everything is working just fine. When finish JWT I will announce the refactored version.

**Comment by yakuter** [comment]
Done and merged!
