### ISSUE TITLE
JWT auth sign in endpoint is needed

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-server#79]
Well, I removed all the gin framework codes from codebase in **nongin** branch. Now we need to add JWT authentication.

The stack I want to use:
net/http
mux router
negroni middleware
jwt-go (https://github.com/dgrijalva/jwt-go)

In this issue we need 3 endpoints;
/auth/signin
/auth/refresh
/auth/logout

HS256 signin method jwt-go must be used. There is example here:
https://godoc.org/github.com/dgrijalva/jwt-go#example-New--Hmac

I know this is a big job but do anyone wants to work on this?

**Comment by omerbasoglu-co** [comment]
I have been working on the issue, you can see progress [my branch ](https://github.com/omerbasoglu-co/passwall-server/tree/jwt-auth-sign). I will continue it on tomorrow. fyi @yakuter 

- redesigned main.go (router and negroni)
- deleted unused code

**Comment by yakuter** [comment]
Thank you @omerbasoglu-co
