### ISSUE TITLE
Why there is always 2 requests in logs

### ISSUE THREAD

**Issue by yakuter** [pass-wall/passwall-server#86]
When I look at logs, even I do one GET request with postman, logs shows that there is 2 requests. I don't know if it is normal with negroni but we better look for this.
![Screen Shot 2020-05-01 at 00 36 36](https://user-images.githubusercontent.com/3696314/80763894-31f0eb00-8b48-11ea-996e-1e9c8c8c9aa0.png)

**Comment by ramazan** [comment]
I'm not sure but according to negroni's documentation, the logger middleware logs request and response. maybe thats why there are two logs

> This middleware logs each incoming request and response.

https://github.com/urfave/negroni#logger
