### ISSUE TITLE
Server / Demo Web page

### ISSUE THREAD

**Issue by selcukgural** [pass-wall/passwall-server#97]
Merhaba,

Demo için kullanılan web sayfasına ulaşılamıyor. (404)

![Capture](https://user-images.githubusercontent.com/5683149/80949447-b8cdee00-8dfc-11ea-9860-dbfaeacb2c62.PNG)

**Comment by safakkizkin** [comment]
Merhaba @selcukgural,

Burası sadece API sorgularına cevap döndürmek için açık durumda arayüz desteği yoktur.

README içerisinde verilen API Dökümanı ile demo web sayfasına istek yaparak test edebilirsin :v:

**Comment by yakuter** [comment]
Web arayüzüne şuradan ulaşabilirsin:

https://passwall-web.herokuapp.com/

**Comment by selcukgural** [comment]
Ohh kaçırmışım, teşekkür ederim 😀
